"""initial schema

Revision ID: 26012188e5bb
Revises:
Create Date: 2026-10-04 00:06:41.962424
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "26012188e5bb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("address_id", sa.String(length=16), nullable=False),
        sa.Column("street_address", sa.Text(), nullable=False),
        sa.Column("postal_city", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("zip", sa.String(length=10), nullable=True),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("units", sa.Integer(), nullable=True),
        sa.Column("use_code", sa.String(length=32), nullable=True),
        sa.Column("use_description", sa.Text(), nullable=True),
        sa.Column("source_dataset", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("address_id"),
    )
    op.create_index(op.f("ix_addresses_postal_city"), "addresses", ["postal_city"], unique=False)
    op.create_index(op.f("ix_addresses_state"), "addresses", ["state"], unique=False)
    op.create_table(
        "change_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("test_id", sa.String(length=16), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("test_type", sa.String(length=24), nullable=True),
        sa.Column("affected_address_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "conflict_flag_address_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_id", "as_of", name="uq_change_result"),
    )
    op.create_index(op.f("ix_change_results_test_id"), "change_results", ["test_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("doc_id", sa.String(length=16), nullable=False),
        sa.Column("jurisdictions", sa.String(length=128), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=True),
        sa.Column("capture", sa.String(length=32), nullable=True),
        sa.Column("retrieved_at", sa.String(length=32), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("text_file", sa.String(length=128), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    op.create_table(
        "extraction_runs",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("doc_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("docs_total", sa.Integer(), nullable=False),
        sa.Column("docs_done", sa.Integer(), nullable=False),
        sa.Column("docs_failed", sa.Integer(), nullable=False),
        sa.Column("rules_extracted", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "address_jurisdictions",
        sa.Column("address_id", sa.String(length=16), nullable=False),
        sa.Column("legal_city", sa.String(length=128), nullable=True),
        sa.Column("legal_state", sa.String(length=2), nullable=True),
        sa.Column("county", sa.String(length=128), nullable=True),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("matched_address", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("place_geoid", sa.String(length=16), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["address_id"], ["addresses.address_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("address_id"),
    )
    op.create_index(
        op.f("ix_address_jurisdictions_legal_city"),
        "address_jurisdictions",
        ["legal_city"],
        unique=False,
    )
    op.create_index(
        op.f("ix_address_jurisdictions_legal_state"),
        "address_jurisdictions",
        ["legal_state"],
        unique=False,
    )
    op.create_table(
        "rules",
        sa.Column("team_rule_id", sa.String(length=64), nullable=False),
        sa.Column("jurisdiction", sa.String(length=128), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("category", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("requirement", sa.Text(), nullable=False),
        sa.Column("key_value", sa.Text(), nullable=True),
        sa.Column("coverage_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("exemptions", sa.Text(), nullable=True),
        sa.Column("overrides", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("interaction", sa.Text(), nullable=True),
        sa.Column("effective_date", sa.String(length=10), nullable=True),
        sa.Column("citation", sa.Text(), nullable=False),
        sa.Column("source_doc_id", sa.String(length=16), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("quoted_span", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("conflict_flag", sa.Boolean(), nullable=False),
        sa.Column("conflict_note", sa.Text(), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_doc_id"], ["documents.doc_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("team_rule_id"),
    )
    op.create_index(op.f("ix_rules_category"), "rules", ["category"], unique=False)
    op.create_index(op.f("ix_rules_jurisdiction"), "rules", ["jurisdiction"], unique=False)
    op.create_index(op.f("ix_rules_level"), "rules", ["level"], unique=False)
    op.create_index(op.f("ix_rules_run_id"), "rules", ["run_id"], unique=False)
    op.create_index(op.f("ix_rules_source_doc_id"), "rules", ["source_doc_id"], unique=False)
    op.create_index(op.f("ix_rules_status"), "rules", ["status"], unique=False)
    op.create_table(
        "lookups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address_id", sa.String(length=16), nullable=False),
        sa.Column("team_rule_id", sa.String(length=64), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("conflict_flag", sa.Boolean(), nullable=False),
        sa.Column("unresolved_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["address_id"], ["addresses.address_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_rule_id"], ["rules.team_rule_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address_id", "team_rule_id", "as_of", name="uq_lookup"),
    )
    op.create_index(op.f("ix_lookups_address_id"), "lookups", ["address_id"], unique=False)
    op.create_index(op.f("ix_lookups_as_of"), "lookups", ["as_of"], unique=False)
    op.create_index(op.f("ix_lookups_result"), "lookups", ["result"], unique=False)
    op.create_index(op.f("ix_lookups_team_rule_id"), "lookups", ["team_rule_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lookups_team_rule_id"), table_name="lookups")
    op.drop_index(op.f("ix_lookups_result"), table_name="lookups")
    op.drop_index(op.f("ix_lookups_as_of"), table_name="lookups")
    op.drop_index(op.f("ix_lookups_address_id"), table_name="lookups")
    op.drop_table("lookups")
    op.drop_index(op.f("ix_rules_status"), table_name="rules")
    op.drop_index(op.f("ix_rules_source_doc_id"), table_name="rules")
    op.drop_index(op.f("ix_rules_run_id"), table_name="rules")
    op.drop_index(op.f("ix_rules_level"), table_name="rules")
    op.drop_index(op.f("ix_rules_jurisdiction"), table_name="rules")
    op.drop_index(op.f("ix_rules_category"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_address_jurisdictions_legal_state"), table_name="address_jurisdictions")
    op.drop_index(op.f("ix_address_jurisdictions_legal_city"), table_name="address_jurisdictions")
    op.drop_table("address_jurisdictions")
    op.drop_table("extraction_runs")
    op.drop_table("documents")
    op.drop_index(op.f("ix_change_results_test_id"), table_name="change_results")
    op.drop_table("change_results")
    op.drop_index(op.f("ix_addresses_state"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_postal_city"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
