"""pipeline: audit trail, extraction cache, document typing

Revision ID: a1b443d62853
Revises: 26012188e5bb
Create Date: 2026-10-04 00:50:26.282182
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a1b443d62853'
down_revision = '26012188e5bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_channel'), 'audit_entries', ['channel'], unique=False)
    op.create_index(op.f('ix_audit_entries_created_at'), 'audit_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_entries_run_id'), 'audit_entries', ['run_id'], unique=False)
    op.create_table('extraction_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_extraction_cache_doc_id'), 'extraction_cache', ['doc_id'], unique=False)
    op.add_column('documents', sa.Column('doc_type', sa.String(length=24), nullable=True))
    op.add_column('documents', sa.Column('tier', sa.String(length=4), nullable=True))
    # server_default backfills the 87 existing rows; NOT NULL would fail otherwise.
    op.add_column(
        'documents',
        sa.Column(
            'origin', sa.String(length=24), nullable=False,
            server_default='provided',
        ),
    )
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('doc_type_reason', sa.Text(), nullable=True))
    op.add_column(
        'documents',
        sa.Column(
            'doc_type_confirmed', sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ),
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_tier'), 'documents', ['tier'], unique=False)
    op.add_column('rules', sa.Column('group_key', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('tier', sa.String(length=4), nullable=True))
    op.add_column(
        'rules',
        sa.Column(
            'other_sources', postgresql.JSONB(astext_type=sa.Text()),
            nullable=False, server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column('rules', sa.Column('citation_evidence', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_rules_group_key'), 'rules', ['group_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_group_key'), table_name='rules')
    op.drop_column('rules', 'citation_evidence')
    op.drop_column('rules', 'other_sources')
    op.drop_column('rules', 'tier')
    op.drop_column('rules', 'group_key')
    op.drop_index(op.f('ix_documents_tier'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'doc_type_confirmed')
    op.drop_column('documents', 'doc_type_reason')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'origin')
    op.drop_column('documents', 'tier')
    op.drop_column('documents', 'doc_type')
    op.drop_index(op.f('ix_extraction_cache_doc_id'), table_name='extraction_cache')
    op.drop_table('extraction_cache')
    op.drop_index(op.f('ix_audit_entries_run_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_created_at'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_channel'), table_name='audit_entries')
    op.drop_table('audit_entries')
    # ### end Alembic commands ###
